PREFIX aida: <https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/InterchangeOntology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

DELETE {
    ?cluster a aida:SameAsCluster .
    ?cluster aida:prototype ?prototype .
    ?cluster aida:system ?system .

    ?clusterMembership a aida:ClusterMembership ;
        aida:cluster ?cluster ;
        aida:clusterMember ?clusterMember ;
        aida:confidence ?conf ;
        aida:system ?sys .
    ?conf a aida:Confidence ;
        aida:confidenceValue ?cv ;
        aida:system ?sys_conf
}
WHERE {
    ?cluster a aida:SameAsCluster .
    ?cluster aida:prototype ?prototype .
    ?cluster aida:system ?system .

    ?clusterMembership a aida:ClusterMembership ;
        aida:cluster ?cluster ;
        aida:clusterMember ?clusterMember ;
        aida:confidence ?conf ;
        aida:system ?sys .
    ?conf a aida:Confidence ;
        aida:confidenceValue ?cv ;
        aida:system ?sys_conf
}
