PREFIX aida: <https://tac.nist.gov/tracks/SM-KBP/2018/ontologies/InterchangeOntology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?e ?type ?doc ?text ?translate ?ent
WHERE {
    ?e a aida:Event;
       aida:justifiedBy [
    		aida:source ?doc ;
    		skos:prefLabel ?text ] .
    OPTIONAL {
      ?j aida:privateData [
      		aida:jsonContent ?translate ;
        	aida:system <http://www.rpi.edu/EDL_Translation> ] .
    }
    ?r rdf:subject ?e ;
       rdf:predicate rdf:type ;
       rdf:object ?type .
	OPTIONAL {
      ?r2 rdf:subject ?e ;
          rdf:object ?ent .
      ?ent a aida:Entity .
	}
}
