insert {GRAPH <http://www.isi.com/supergraph> {
    ?p aida:justifiedBy ?j .
}}
where {
    GRAPH <http://www.isi.com/supergraph> {
        ?c aida:prototype ?p .
        ?mem aida:cluster ?c ;
             aida:clusterMember ?x .
    }
    ?x aida:justifiedBy ?j .
}
