insert {GRAPH <http://www.isi.com/supergraph> {
    ?p aida:justifiedBy ?j .
}}
where {
    ?c aida:prototype ?p .
    ?mem aida:cluster ?c ;
         aida:clusterMember ?x .
    ?x aida:justifiedBy ?j .
}
