insert {GRAPH <http://www.isi.com/supergraph> {
    [] a rdf:Statement ;
       rdf:subject ?evtRelProto ;
       rdf:predicate ?p ;
       rdf:object ?entProto ;
  	   aida:count ?cnt .
}}
where {
  select ?evtRelProto ?p ?entProto (count(*) as ?cnt)
  where {
      ?evtRelC aida:prototype ?evtRelProto .
      ?mem1 aida:cluster ?evtRelC ;
           aida:clusterMember ?evtRel .
      ?entC aida:prototype ?entProto .
      ?mem2 aida:cluster ?entC ;
           aida:clusterMember ?ent .
      ?state rdf:subject ?evtRel ;
             rdf:predicate ?p ;
             rdf:object ?ent .
  } groupby ?evtRelProto ?p ?entProto orderby desc(?cnt)
}
